let songs = [
    {songName: "Hai Junoon", filePath: "songs/1.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Barri", filePath: "songs/2.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Maiya Mainu", filePath: "songs/3.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Nazm Nazm", filePath: "songs/4.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Pasoori", filePath: "songs/5.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Chaand Baaliyan", filePath: "songs/6.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Do Gallan", filePath: "songs/7.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Tumhari Tasveer Ke Sahare", filePath: "songs/8.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Titliyan", filePath: "songs/9.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Raatan Lambiyan", filePath: "songs/10.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Despacito", filePath: "songs/11.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Shape of you", filePath: "songs/12.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Srivalli", filePath: "songs/13.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Zalma", filePath: "songs/14.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Hum Nashe Mein Toh Nahin", filePath: "songs/15.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Dil Galti Kar Baitha Hai", filePath: "songs/16.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Journey Song", filePath: "songs/17.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Gallan Goodiyaan", filePath: "songs/18.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Jhoom", filePath: "songs/19.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Closer", filePath: "songs/20.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Mast Nazron", filePath: "songs/21.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "Meri jaan", filePath: "songs/22.mp3", coverPath: "songs/cover1.jpg"},
    {songName: "KK Mashup", filePath: "songs/23.mp3", coverPath: "songs/cover1.jpg"},
]